FROM alpine:3

LABEL author="Pingki Tornanda Pasaribu"
LABEL company="Soles Space" website="https://www.SolesSpace.com/"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.text"

CMD cat "hello/world.text"